# Jekyll Specific Stuff
markdown: kramdown
pygments: true
permalink: /posts/:title
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Oliver P. Hoffmann
baseurl:   # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: '霍夫曼'
email: 
twitter: wiemanindenwald
icon_url: http://res.cloudinary.com/ontore/image/upload/v1457283748/YVXbTeoF_cdipm1.jpg
disqus_shortname: wiemanindenwald

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: contact
footer_description: 
social_links_title: 
# github_url: https://github.com/ontore
flickr_url: 
# instagram_url: https://www.instagram.com/ontore/
vimeo_url: 
# facebook_url: https://www.facebook.com/wiemanindenwald
# google_plus_url: https://plus.google.com/u/0/+OliverHoffmannAustria
# pinterest_url: https://www.pinterest.com/ontore/
tumblr_url: 
# linkedin_url: https://at.linkedin.com/in/ontore
dribbble_url: 
lastfm_url: 
rdio_url: 
spotify_url: 
# skype_url: skype:oliver.hoffmann?call
# soundcloud_url: https://soundcloud.com/ontore
behance_url: 
